#!/usr/bin/env bash
#
# build_offline_bundle.sh — produce a self-contained bundle for the air-gapped host.
#
# RUN THIS ON A MACHINE WITH INTERNET AND DOCKER, not on the air-gapped server.
# The image build pulls python:3.11-slim and apt-installs ffmpeg; neither is
# reachable from inside the closed network.
#
# Output: dist/recog-offline-<version>.tar.gz containing
#   recog-backend-<version>.tar.gz   docker image (docker save | gzip)
#   docker-compose.yml               deployment definition
#   .env.recog.example               configuration template
#   install_offline.sh               installer to run on the target host
#   OFFLINE_DEPLOY.md                step-by-step instructions
#   SHA256SUMS                       integrity check for the transfer
#
# Usage:
#   scripts/deploy/build_offline_bundle.sh [version] [platform]
#
#   version   image tag to build      (default: skHynix-offline-<date>)
#   platform  target architecture     (default: linux/amd64)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

VERSION="${1:-skHynix-offline-$(date +%Y%m%d)}"
PLATFORM="${2:-linux/amd64}"
IMAGE_REPO="recog-backend"
IMAGE_REF="${IMAGE_REPO}:${VERSION}"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

BUNDLE_NAME="recog-offline-${VERSION}"
BUNDLE_DIR="${STAGE}/${BUNDLE_NAME}"
DIST_DIR="${REPO_ROOT}/dist"

log() { printf '\033[1;34m[build]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[build] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not found. Run this on a build machine with Docker."
docker version >/dev/null 2>&1 || die "docker daemon is not responding."

# The air-gapped server is almost certainly x86_64 while build machines are
# often Apple Silicon. An arm64 image will not start there, so pin explicitly.
HOST_ARCH="$(uname -m)"
log "build host arch: ${HOST_ARCH}  ->  target platform: ${PLATFORM}"
if [[ "$PLATFORM" == "linux/amd64" && ( "$HOST_ARCH" == "arm64" || "$HOST_ARCH" == "aarch64" ) ]]; then
    log "cross-building amd64 on arm64 (slower; requires buildx/qemu)"
fi

mkdir -p "$BUNDLE_DIR" "$DIST_DIR"

# ---------------------------------------------------------------- build image
log "building ${IMAGE_REF}"
if docker buildx version >/dev/null 2>&1; then
    docker buildx build \
        --platform "$PLATFORM" \
        --tag "$IMAGE_REF" \
        --load \
        --file Dockerfile \
        .
else
    log "buildx unavailable; falling back to plain build (platform flag ignored)"
    docker build --tag "$IMAGE_REF" --file Dockerfile .
fi

BUILT_ARCH="$(docker image inspect "$IMAGE_REF" --format '{{.Os}}/{{.Architecture}}')"
log "built image platform: ${BUILT_ARCH}"
if [[ "$BUILT_ARCH" != "$PLATFORM" ]]; then
    log "WARNING: built ${BUILT_ARCH} but target is ${PLATFORM}."
    log "         The container will fail to start on the deploy host."
    log "         Install buildx/qemu, or build on a ${PLATFORM} machine."
fi

# ----------------------------------------------------------------- save image
log "saving image (this takes a minute)"
docker save "$IMAGE_REF" | gzip -9 > "${BUNDLE_DIR}/${IMAGE_REPO}-${VERSION}.tar.gz"

# ------------------------------------------------------------ assemble bundle
log "assembling bundle"
install -m 0644 deploy/docker-compose.yml       "${BUNDLE_DIR}/docker-compose.yml"
install -m 0644 deploy/.env.recog.example       "${BUNDLE_DIR}/.env.recog.example"
install -m 0644 deploy/OFFLINE_DEPLOY.md        "${BUNDLE_DIR}/OFFLINE_DEPLOY.md"
install -m 0755 scripts/deploy/install_offline.sh "${BUNDLE_DIR}/install_offline.sh"

# Record what the installer should load, so it never has to guess.
cat > "${BUNDLE_DIR}/bundle.env" <<EOF
# Generated by build_offline_bundle.sh — do not edit.
BUNDLE_IMAGE_REF=${IMAGE_REF}
BUNDLE_IMAGE_FILE=${IMAGE_REPO}-${VERSION}.tar.gz
BUNDLE_VERSION=${VERSION}
BUNDLE_PLATFORM=${BUILT_ARCH}
BUNDLE_BUILT_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)
BUNDLE_GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
EOF

( cd "$BUNDLE_DIR" && find . -type f ! -name SHA256SUMS -print0 \
    | sort -z \
    | xargs -0 shasum -a 256 > SHA256SUMS )

# -------------------------------------------------------------------- package
OUT="${DIST_DIR}/${BUNDLE_NAME}.tar.gz"
log "packaging ${OUT}"
tar -czf "$OUT" -C "$STAGE" "$BUNDLE_NAME"
shasum -a 256 "$OUT" > "${OUT}.sha256"

log "done"
echo
echo "  bundle : ${OUT}"
echo "  size   : $(du -h "$OUT" | cut -f1)"
echo "  sha256 : $(cut -d' ' -f1 < "${OUT}.sha256")"
echo
echo "Transfer both files to the air-gapped host, then:"
echo "  tar xzf ${BUNDLE_NAME}.tar.gz"
echo "  cd ${BUNDLE_NAME}"
echo "  ./install_offline.sh"
